CREATE SEQUENCE GEN_DefaultSeq START WITH 1 INCREMENT BY 1 CACHE 20 NOORDER NOCYCLE; 

CREATE SEQUENCE GEN_UnidadOrganica START WITH 100000 INCREMENT BY 1 CACHE 250 NOORDER NOCYCLE; 
CREATE SEQUENCE GEN_AppOperation START WITH 60000 INCREMENT BY 1 CACHE 250 NOORDER NOCYCLE; 
CREATE SEQUENCE GEN_Requests START WITH 5000 INCREMENT BY 1 CACHE 50 NOORDER NOCYCLE; 
CREATE SEQUENCE GEN_RequestsPDF START WITH 5000 INCREMENT BY 1 CACHE 50 NOORDER NOCYCLE; 

commit;

exit;
